//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Inputs/Inputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inputs"",
    ""maps"": [
        {
            ""name"": ""onFoot"",
            ""id"": ""70bbff8d-885e-4600-991b-0c58076c2dc7"",
            ""actions"": [
                {
                    ""name"": ""VerticalUpMovement"",
                    ""type"": ""Value"",
                    ""id"": ""c6643643-413c-4493-8798-07e21711239f"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""VerticalDownMovement"",
                    ""type"": ""Value"",
                    ""id"": ""0157d371-eff4-4ce2-ad9f-6192d9ae28d2"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HorizontalLeftMovement"",
                    ""type"": ""Value"",
                    ""id"": ""b3e37726-4518-4a79-8234-2ed6fb0d55ca"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HorizontalRightMovement"",
                    ""type"": ""Value"",
                    ""id"": ""c473d8e1-b0fc-4385-8805-f6685c381b4f"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""538b9d8a-084f-4b59-a6c9-89d6568e37bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""6c8434e4-6105-4448-adfa-4e4bac4994b4"",
                    ""path"": ""1DAxis"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalUpMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""5a9c2297-d918-4f43-b64f-7fcbecc15bed"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalUpMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""3a7295e6-8756-4ea3-9d8f-ad6826045059"",
                    ""path"": ""1DAxis"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalLeftMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""18c900d3-adc5-4b20-8e2a-601005eaab23"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalLeftMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5c0eab83-3bbe-46b8-ae0d-8f082f95e176"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""12a5eb1f-fa38-49ef-894a-3b3b6ca374c9"",
                    ""path"": ""1DAxis"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalDownMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""11534717-c5e5-445c-8444-02e9cdfdc7d6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalDownMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""2ce9f2e6-598a-4f10-8818-6ec0a97f40df"",
                    ""path"": ""1DAxis"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalRightMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""c35d3bbd-d854-4f2d-8bd5-6803266e545e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalRightMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // onFoot
        m_onFoot = asset.FindActionMap("onFoot", throwIfNotFound: true);
        m_onFoot_VerticalUpMovement = m_onFoot.FindAction("VerticalUpMovement", throwIfNotFound: true);
        m_onFoot_VerticalDownMovement = m_onFoot.FindAction("VerticalDownMovement", throwIfNotFound: true);
        m_onFoot_HorizontalLeftMovement = m_onFoot.FindAction("HorizontalLeftMovement", throwIfNotFound: true);
        m_onFoot_HorizontalRightMovement = m_onFoot.FindAction("HorizontalRightMovement", throwIfNotFound: true);
        m_onFoot_Interaction = m_onFoot.FindAction("Interaction", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // onFoot
    private readonly InputActionMap m_onFoot;
    private IOnFootActions m_OnFootActionsCallbackInterface;
    private readonly InputAction m_onFoot_VerticalUpMovement;
    private readonly InputAction m_onFoot_VerticalDownMovement;
    private readonly InputAction m_onFoot_HorizontalLeftMovement;
    private readonly InputAction m_onFoot_HorizontalRightMovement;
    private readonly InputAction m_onFoot_Interaction;
    public struct OnFootActions
    {
        private @Inputs m_Wrapper;
        public OnFootActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @VerticalUpMovement => m_Wrapper.m_onFoot_VerticalUpMovement;
        public InputAction @VerticalDownMovement => m_Wrapper.m_onFoot_VerticalDownMovement;
        public InputAction @HorizontalLeftMovement => m_Wrapper.m_onFoot_HorizontalLeftMovement;
        public InputAction @HorizontalRightMovement => m_Wrapper.m_onFoot_HorizontalRightMovement;
        public InputAction @Interaction => m_Wrapper.m_onFoot_Interaction;
        public InputActionMap Get() { return m_Wrapper.m_onFoot; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnFootActions set) { return set.Get(); }
        public void SetCallbacks(IOnFootActions instance)
        {
            if (m_Wrapper.m_OnFootActionsCallbackInterface != null)
            {
                @VerticalUpMovement.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnVerticalUpMovement;
                @VerticalUpMovement.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnVerticalUpMovement;
                @VerticalUpMovement.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnVerticalUpMovement;
                @VerticalDownMovement.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnVerticalDownMovement;
                @VerticalDownMovement.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnVerticalDownMovement;
                @VerticalDownMovement.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnVerticalDownMovement;
                @HorizontalLeftMovement.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnHorizontalLeftMovement;
                @HorizontalLeftMovement.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnHorizontalLeftMovement;
                @HorizontalLeftMovement.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnHorizontalLeftMovement;
                @HorizontalRightMovement.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnHorizontalRightMovement;
                @HorizontalRightMovement.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnHorizontalRightMovement;
                @HorizontalRightMovement.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnHorizontalRightMovement;
                @Interaction.started -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInteraction;
                @Interaction.performed -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInteraction;
                @Interaction.canceled -= m_Wrapper.m_OnFootActionsCallbackInterface.OnInteraction;
            }
            m_Wrapper.m_OnFootActionsCallbackInterface = instance;
            if (instance != null)
            {
                @VerticalUpMovement.started += instance.OnVerticalUpMovement;
                @VerticalUpMovement.performed += instance.OnVerticalUpMovement;
                @VerticalUpMovement.canceled += instance.OnVerticalUpMovement;
                @VerticalDownMovement.started += instance.OnVerticalDownMovement;
                @VerticalDownMovement.performed += instance.OnVerticalDownMovement;
                @VerticalDownMovement.canceled += instance.OnVerticalDownMovement;
                @HorizontalLeftMovement.started += instance.OnHorizontalLeftMovement;
                @HorizontalLeftMovement.performed += instance.OnHorizontalLeftMovement;
                @HorizontalLeftMovement.canceled += instance.OnHorizontalLeftMovement;
                @HorizontalRightMovement.started += instance.OnHorizontalRightMovement;
                @HorizontalRightMovement.performed += instance.OnHorizontalRightMovement;
                @HorizontalRightMovement.canceled += instance.OnHorizontalRightMovement;
                @Interaction.started += instance.OnInteraction;
                @Interaction.performed += instance.OnInteraction;
                @Interaction.canceled += instance.OnInteraction;
            }
        }
    }
    public OnFootActions @onFoot => new OnFootActions(this);
    public interface IOnFootActions
    {
        void OnVerticalUpMovement(InputAction.CallbackContext context);
        void OnVerticalDownMovement(InputAction.CallbackContext context);
        void OnHorizontalLeftMovement(InputAction.CallbackContext context);
        void OnHorizontalRightMovement(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
    }
}
