#ifndef ARDUINOCONTROLLER_ENUMS_H
#define ARDUINOCONTROLLER_ENUMS_H

enum CARD_NAME {
    OTHER = 999,
    CHZ1 = 1,
    CHZ2,
    CHZ3,
    CHZ4,
    TAG,
    TSP
};

enum ERR_TYPE {
    NO_CARD_DETECTED = -100,
    CARD_NOT_RECOGNISED = -200,
    CARD_NOT_EXPECTED = -300,
};

enum MENU_TYPE {
    MAIN_MENU = 1,
    TIMER_MENU,
    SETTINGS_MENU
};

enum TIMER_ACTIONS {
    TIMER_A_PAUSE = 1,
    TIMER_A_RESET,
    TIMER_A_SWITCH,
    TIMER_A_SHOW
};

enum SETTINGS_ACTIONS {
    SETTINGS_SYNC = 1,
    SETTINGS_REBOOT,
    SETTINGS_CONTRAST
};

enum SERIAL_MESSAGE_CODE {
    READY,
    SYNC,
    REBOOT,
    TIMER_PP,
    TIMER_RST,
    TIMER_SWITCH,
    TIMER_SHOW
};

enum CARD_MODE {
    NORMAL=1,
    TIMER
};

#endif //ARDUINOCONTROLLER_ENUMS_H